CREATE TABLE IF NOT EXISTS public.user_movie_state (
  state_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id bigint NOT NULL,
  movie_id bigint NOT NULL,
  watched boolean NOT NULL DEFAULT false,
  CONSTRAINT uq_user_movie UNIQUE (user_id, movie_id),
  CONSTRAINT fk_user_movie_state_user
    FOREIGN KEY (user_id) REFERENCES public.users(user_id) ON DELETE CASCADE,
  CONSTRAINT fk_user_movie_state_movie
    FOREIGN KEY (movie_id) REFERENCES public.movie(movie_id) ON DELETE CASCADE
);