name: CI

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21
          cache: maven

      - name: Test & Package (unit tests only)
        run: mvn -B -Dtest='*Test,!HorrorPoolApplicationTests' clean package

      - name: Upload JAR
        uses: actions/upload-artifact@v4
        with:
          name: app-jar
          path: target/horror_pool-0.0.1-SNAPSHOT.jar

  smoke:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v4

      - name: Download JAR
        uses: actions/download-artifact@v4
        with:
          name: app-jar
          path: target

      - name: Compose up
        run: docker compose up --build -d

      - name: Wait for /actuator/health
        run: |
          for i in {1..90}; do
            if curl -fsS http://localhost:8080/actuator/health | grep -q '"status":"UP"'; then
              echo "App is UP"; exit 0
            fi
            echo "Waiting app... ($i)"; sleep 2
          done
          echo "App did not become healthy in time"; exit 1

      - name: Print logs on failure
        if: failure()
        run: docker compose logs --no-color

      - name: Compose down
        if: always()
        run: docker compose down -v